spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.92:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: quc@2022@din # windows quc@2022@din

# 配置mybatis的规则
mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 9998